[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="mc"
version="2025.0.0"

[tool.pytest.ini_options]
filterwarnings="ignore::DeprecationWarning"

[tool.setuptools]
packages = { find = { where = ["mc"] } } 